### ISSUE TITLE
Translate assessment units into reporting units 

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-dev/COMPEAT#2]
Assessment units used to calculate the indicator and assessment result are defined by contracting parties nationally.

However it seems like OSPAR would like to report the assessment result using the OSPAR reporting units.

How should Assessment Units results be translated into Reporting Units?

**Comment by philipaxe** [comment]
Isn't this only an issue if reporting units differ from assessment units? Is this the case anywhere? Aren't the OSPAR reporting units (the nested scheme) aligned with national assessment units. Apologies for my ignorance....

**Comment by philipaxe** [comment]
Hmmm. OK. I suspect for our units it’s a case that minor revisions of boundaries haven’t fed back up to OSPARs central reporting units GIS file. We’ve had a process of updating our waterframework waterbodies as better depth data has come in, and there’s also a project developing an improved baseline and EEZ description to account for land uplift etc. If it’s the same for everybody then maybe we need an OSPAR product every couple of years to ensure that the reporting units are consistent.

/Philip

Från: HjalteParner [mailto:notifications@github.com]
Skickat: den 12 december 2018 18:27
Till: ices-tools-dev/OEAT <OEAT@noreply.github.com>
Kopia: Philip Axe <philip.axe@havochvatten.se>; Comment <comment@noreply.github.com>
Ämne: Re: [ices-tools-dev/OEAT] Translate assessment units into reporting units (#2)


Initially I also thought that the OSPAR reporting units was used for the actual assessment. However that's unfortunately not the case which also was confirmed by the OSPAR secretariat. Even the Swedish assessment units doesn't align completely with the OSPAR reporting units.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://url10.mailanyone.net/v1/?m=1gX8HU-000GJQ-4r&i=57e1b682&c=mGkr3Kv9f9Kf8r_lsSUDrY_H1DCDb9BGuWr4STQ2Eoxpl3efaBn-BUXevnwtAjP8Jf9S1FMG-AUs77pdMH1er6AhU0ycW9GapAPphEuBhqHKVSoGAKUBCpjXxeEzU6dUXmFdY1Oy_qc5Uf3V5tLcaVBX0xgxbPM5N33UIaFrL7VH3uxsoCJ02x2N9qkDypYfRTDUWepqXprpvPqtSuteriyOf0B5OJyKiyZq7OL2OndchJa14j5-QYaej0THo6JzzMTpK0IRJkAswWirv7oVuZQrLyJ_PNxwHEks8ApMZU4>, or mute the thread<https://url10.mailanyone.net/v1/?m=1gX8HU-000GJQ-4r&i=57e1b682&c=3wn_sZRrygbFFtSPrWBZXMfN7JyiC30fUdBInFUEz768UNDh-nonPWI702QSy_rp4dXOBw84PmO70OzgpaocO1uQj7fCMYtP06OvxCQ9H9ersVqz9FpGWsh2xdckRh9yhouGpkdpA80v8lulGPQdU3bJf-nTUog-5YTDNrBTEuCuicsfq791zR6jI06WxwvWJP2hBoDENFhxESajj35M5sLacXx-dwr1QTV8bWX8XpaZZIwZr4J0taS7zDsOg-sDMac7KLACq3i51KWpvr1A5WI3kco7luq0lXUJ_TgOeVtYQVkc7ipozQWeuOOck-pgBGlwyHkN1AN7v6UDiAVgUA>.

Havs- och vattenmyndigheten behandlar dina personuppgifter i enlighet med dataskyddsförordningen och myndighetens dataskyddspolicy, läs mer på www.havochvatten.se/sa-behandlar-hav-dina-personuppgifter<https://www.havochvatten.se/sa-behandlar-hav-dina-personuppgifter>
SwAM processes your personal data in accordance with the General Data Protection Regulation (GDPR) and our Data Protection Policy, see www.havochvatten.se/sa-behandlar-hav-dina-personuppgifter<https://www.havochvatten.se/sa-behandlar-hav-dina-personuppgifter>

**Comment by HjalteParner** [comment]
Think this issue is not relevant anymore
