### ISSUE TITLE
Calculation of DIN

### ISSUE THREAD

**Issue by kawess** [ices-tools-dev/COMPEAT#5]
Is it included in the code that DIN should only be calculated if NO3  (or NO3+NO2) is present? This is because NO3 is biggest contribution to DIN in surface waters.

**Comment by HjalteParner** [comment]
Yes, the code referenced below does exactly this e.g. if all variables Nitrate, Nitrite and Ammonium are NA or Nitrate is NA Then DIN is NA, otherwise DIN is the sum of the present variables.  In the ICES database its implicit assumed that if Nitrate is alone, its actual Nitrate+Nitrite.

``
coalesce <- function(x) {
  if (all(is.na(x)) | is.na(x[1])){
    NA
  } else {
    sum(x, na.rm = TRUE)
  } 
}
wk$DIN..umol.l. <- apply(wk[, list(Nitrate..umol.l., Nitrite..umol.l., Ammonium..umol.l.)], 1, coalesce)
``

**Comment by kawess** [comment]
Great!

//Karin

Från: HjalteParner [mailto:notifications@github.com]
Skickat: den 4 februari 2019 23:52
Till: ices-tools-dev/COMPEAT
Kopia: Wesslander Karin; Author
Ämne: Re: [ices-tools-dev/COMPEAT] Calculation of DIN (#5)


Yes, the code referenced below does exactly this e.g. if all variables Nitrate, Nitrite and Ammonium are NA or Nitrate is NA Then DIN is NA, otherwise DIN is the sum of the present variables. In the ICES database its implicit assumed that if Nitrate is alone, its actual Nitrate+Nitrite.

coalesce <- function(x) { if (all(is.na(x)) | is.na(x[1])){ NA } else { sum(x, na.rm = TRUE) } } wk$DIN..umol.l. <- apply(wk[, list(Nitrate..umol.l., Nitrite..umol.l., Ammonium..umol.l.)], 1, coalesce)
