### ISSUE TITLE
HEAT/HOLAS uncertainty that's probably relevant for OSPAR too

### ISSUE THREAD

**Issue by philipaxe** [ices-tools-dev/COMPEAT#8]
Hi Hjalte, 
I was in looking at the HEAT 2011 - 2016 results for unit SWE-023. I was trying to check the wDIN and wTN assessments. Changing from one indicator to another seems to "upset" the interface, so in the end I ended up with what looks like all the data for the area, even though the label at the top says Dissolved Inorganic Nitrogen. I suspected that this had happened as I had ended up with a long list of assessment units that appeared to repeat. When I filtered to just the unit I wanted, it became clearer. Attempting to download the data didn't help (download button) as it only gave me the offshore units. Is this a problem/feature of the interface for both HELCOM & OSPAR? Is it a problem with cache-clearing? I'm using Chrome 72.0.3626.121.
![Skärmklipp-HEAT confusion](https://user-images.githubusercontent.com/45823338/54682230-a0264a00-4b0e-11e9-8e21-ca6a9bf971c6.PNG)

I attach a screen grab 
/Philip

**Comment by HjalteParner** [comment]
Hi Philip,

This seems to be a issue for both interfaces and seem to be a filter issue. I will get it fixed asap.

Thanks for noticing, Hjalte

**Comment by HjalteParner** [comment]
You should now been able to download all indicators for all assessment units including SWE-023!

As a temporary fix to the filter issue, what happens if you when the issue shows temporarily switch to the map tab and back to the indicator tab. Here it seems to solve the issue.

However if I then apply another filter the issue happens again and I can then solve it ones more by temporarily switching to the map tab and back ... still need to look into this annoying issue!

**Comment by HjalteParner** [comment]
Interface filtering / sorting issue should now be solved
